### ISSUE TITLE
[BUG] ConceptDescriptions "Create <- SMEs (all)" and "Create <- this" not working directlty

### ISSUE THREAD

**Issue by foprs** [eclipse-aaspe/package-explorer#251] opened 2024-09-28 15:44 UTC
When loading an AASX without existing ConceptDescriptions the click on the button "**Create <- SMEs (all)**" for SM or "**Create <- this**" for a SME leads to an error. 

Error: "Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: Object reference not set to an instance of an object. Object reference not set to an instance of an object. at ..."

When creating an empty ConceptDescription before with "Create empty" it works afterwards.

![image](https://github.com/user-attachments/assets/118ee0dc-7da1-40d5-a799-1bc65d5e575d)

**Comment by juileetikekar** [comment] 2024-10-14 12:02
Hi @foprs,

Please try the latest version of the AASPE. The issue is fixed in this version.

![image](https://github.com/user-attachments/assets/35931376-53de-450f-9483-de8842b8ac81)

**Closed by juileetikekar** 2024-10-14 12:02 UTC
Labels: bug
