### ISSUE TITLE
"Export OPC UA Nodeset2.xml", "Export AAS as i4aas-nodeset" and "Serve AAS as REST" do not work properly.

### ISSUE THREAD

**Issue by MartinAlejandroBaer** [eclipse-aaspe/package-explorer#187] opened 2024-03-18 09:32 UTC
**Describe the bug**
Since version "AASX Package Explorer V3 2023-09-12.alpha" I have detected several bugs: 
- "Export OPC UA Nodeset2 ..": The generated .xml file does not allow to create an OPC UA server instance using the Python library "opcua-asyncio" due to error in the node definition. (The parent node id does not to refer to a valid node. (BadParentNodeIdInvalid)). This worked correctly in the version prior to "AASX Package Explorer V3 2023-09-12.alpha" 
- "Export AAS as i4aas-nodeset ..": The file is not generated.
- "Serve AAS as REST .." features..": The server instance is not created and the pop-up window does not appear.

**Export OPC UA Nodeset2**
**To Reproduce**
1. Go to 'File' - > 'Export'
2. Click on 'Export OPC UA Nodeset2.xml (via UA server plug-in)'
3. Save the .xml file.
4. Create an OPC UA server instance with the generated .xml file.

**Expected behavior**
The file should be importable without errors using the Python library for OPC UA "opcua-asyncio" to mount an OPC UA server.
**Export AAS as i4aas-nodeset**
**To Reproduce**
1. Go to 'File' - > 'Export'
5. Click on 'Export AAS as i4aas-nodeset ..'
6. Save the .xml file

**Expected behavior**
The file should be generated with corresponding node structure.

**Serve AAS as REST**
**To Reproduce**
1. Go to 'File' - > 'Server'
2. Click on 'Serve AAS as REST ...'

**Expected behavior**
The server should be created and display the traditional blue screen indicating all events.

I have checked these issues on two different computers with the same results.

**Desktop 1**
 - OS: Windows 10
 - Version 22H2

**Desktop 2**
 - OS: Windows 11
 - Version 23H2

**Comment by MichaelHoffmeisterFesto** [comment] 2024-05-12 19:37
Hello,

let me state the current state.

# "Export OPC UA Nodeset2 ..": 

Over the course of multiple years, I put severe efforts into this, trying to keep the idea of I4AAS at live, which was discontinued from the OPC foundation. By some migration for the meta model V2 to V3, it is in some intermediate state. It is too painfull to delete and too outdated to be useful ;-)

And yes, I've never tested it with Python; I've only used the UA Expert to demenstrate it.

If there is a specific need from your side, I could try to do a quick fix on this node issue. But this would not imply that I would again spend hours over hours to guess what to do on the OPC library to get something working. It is a tainted miracle.

Elsewise I would propose to put a "do not use" warning on it.

# "Export AAS as i4aas-nodeset .."

This function was maintained by some other collaborators and is, as far as I knonw, not longer maintained.

I would propose to put a "do not use" warning on it or even delete it, as I have no hope, that it will function again.

# "Serve AAS as REST .." 

Due to the course of reworking the aasx-server classes, this was shut down. I would have the hope that at some point in time, this would get up again.

**Comment by MartinAlejandroBaer** [comment] 2024-05-12 20:33
Dear Michael Hoffmeister,

thank you very much for your reply.

Perfect. Understood with “Export AAS as i4aas-nodeset ..” and “Serve AAS as REST ..” functionalities. I've just reported the issue because the options were there. But I was not aware about the history and plans behind it. 

Nevertheless, I would suggest to fix the feature "**Export OPC UA Nodeset2 ..**" or release some new similar feature, because it is extremely useful to populate the nodes of an OPC UA server with the information model generated based on the definitions of the AAS. We even had the opportunity to make several practical implementations that allowed us to deploy the AAS as a service (which from my perspective, is one of the most important points to cover with the AAS). I believe this feature will be useful for future practical implementations of the industrial environment (allowing a bidirectional connection from OT to IT levels)

I also assumed that there was some inconvenience with the migration from version v2 to v3, due to the internal changes that I have observed. However, I could send you one very basic Python script to reproduce the issue and check if it is possible to fix it. I believe that the major inconvenience must be due to the new hierarchical position of the Asset, some elements of Submodels and the new Submodel Elements that have been incorporated.

In case that it is not possible to continue with this feature, I would like to ask you if there is any other possibility to expose the AAS using OPC UA that you find appropriate. Using an instance with a manual mapping process from other services such as REST or MQTT would be a bit impractical and non-interoperable.

Thank you very much in advance.

**Comment by MichaelHoffmeisterFesto** [comment] 2024-05-13 07:47
Hi,

can you provide me with the Python script?

Best

Michael

 

Von: MartinAlejandroBaer ***@***.***> 
Gesendet: Sonntag, 12. Mai 2024 22:34
An: eclipse-aaspe/aaspe ***@***.***>
Cc: MichaelHoffmeisterFesto ***@***.***>; Comment ***@***.***>
Betreff: Re: [eclipse-aaspe/aaspe] "Export OPC UA Nodeset2.xml", "Export AAS as i4aas-nodeset" and "Serve AAS as REST" do not work properly. (Issue #187)

 

Dear Michael Hoffmeister,

thank you very much for your reply.

Perfect. Understood with “Export AAS as i4aas-nodeset ..” and “Serve AAS as REST ..” functionalities. I've just reported the issue because the options were there. But I was not aware about the history and plans behind it.

Nevertheless, I would suggest to fix the feature "Export OPC UA Nodeset2 .." or release some new similar feature, because it is extremely useful to populate the nodes of an OPC UA server with the information model generated based on the definitions of the AAS. We even had the opportunity to make several practical implementations that allowed us to deploy the AAS as a service (which from my perspective, is one of the most important points to cover with the AAS). I believe this feature will be useful for future practical implementations of the industrial environment (allowing a bidirectional connection from OT to IT levels)

I also assumed that there was some inconvenience with the migration from version v2 to v3, due to the internal changes that I have observed. However, I could send you one very basic Python script to reproduce the issue and check if it is possible to fix it. I believe that the major inconvenience must be due to the new hierarchical position of the Asset, some elements of Submodels and the new Submodel Elements that have been incorporated.

In case that it is not possible to continue with this feature, I would like to ask you if there is any other possibility to expose the AAS using OPC UA that you find appropriate. Using an instance with a manual mapping process from other services such as REST or MQTT would be a bit impractical and non-interoperable.

Thank you very much in advance.

**Comment by MartinAlejandroBaer** [comment] 2024-05-13 09:11
Hello,

of course.

```
import logging
import asyncio
import sys
sys.path.insert(0, "..")
from asyncua import Server

async def main():
    _logger = logging.getLogger('asyncua')
    server = Server() # setup our server
    await server.init()
    server.set_endpoint('opc.tcp://XXX.XXX.XXX.XXX:4840/') # Setting the IP and port
    await server.import_xml("AASmodelV2.xml") # Importing the OPCUA ML model generated on the AASX tool.
    # Creating the variables based on the nodes of the OPCUA ML model. 
    # Use the UaModeler or opcua-modeler to verify the number of the nodes.
    Temperature=server.get_node("ns=3;i=119")
    Volume=server.get_node("ns=3;i=126")
    # Setting up the variables in order to overwrite their values
    Temperature.set_writable()
    Volume.set_writable()
    async with server:
        while True: # Infinite loop to overwrite the variables Temperature and Volume
            await asyncio.sleep(3)
            new_temp = await Temperature.get_value() + 0.1
            await Temperature.write_value(new_temp)
            new_vol = await Volume.get_value() + 0.5
            await Volume.write_value(new_vol)       
if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(main(), debug=True)
```
Only the library [asyncua](https://pypi.org/project/asyncua/) needs to be installed

I've also prepared a .zip file ([example.zip](https://github.com/eclipse-aaspe/aaspe/files/15292055/example.zip)) that contains the following:

- Example .aasx with the contents of the information model of the AAS. (AASmodel.aasx)
- An OPC UA Nodeset2 file generated with the AASX PE Version v2023-02-03 (AASmodelV2.xml)
- An OPC UA Nodeset2 file generated with the AASX PE Version v2024-03-05 (AASmodelV3.xml)

Let me know of any other way I can help or contribute.

Regards.

Martin Bär

**Comment by MartinAlejandroBaer** [comment] 2024-05-13 10:22
Hello,

of course.

Here I prepared a repository with a basic example of the OPC UA server [Link](https://github.com/MartinAlejandroBaer/PythonOPC-UA-for-OPC-UA-Nodeset2)

Only the library [asyncua](https://pypi.org/project/asyncua/) needs to be installed

I've also attached three files that contains the following:

- Example .aasx with the contents of the information model of the AAS. (AASmodel.aasx)
- An OPC UA Nodeset2 file generated with the AASX PE Version v2023-02-03 (AASmodelV2.xml)
- An OPC UA Nodeset2 file generated with the AASX PE Version v2024-03-05 (AASmodelV3.xml)

Let me know of any other way I can help or contribute.

Regards.

Martin Bär

**Comment by hadifar** [comment] 2024-11-18 14:52
Any update on this?

**Comment by MichaelHoffmeisterFesto** [comment] 2024-11-18 15:20
Hi, currently not. I haven't touched to topic for quite a while nor did I receive many requests.
In the current branches, we also removed the OPC F sources (the server!) from the main branch, because it was found it would be a blocking point for Eclipse foundation audit.
Therefore, a complete restart is required. :-/

**Comment by MartinAlejandroBaer** [comment] 2024-12-10 16:58
Hello everyone, should I close the issue then?

Best regards.

**Comment by MichaelHoffmeisterFesto** [comment] 2024-12-10 17:47
I would welcome if you would like to close the issue.

Thanks in advance
Michael

**Closed** 2024-12-10 17:50 UTC
Labels: bug, OPC UA
